# Generated by Django 3.1 on 2021-03-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210115_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
