# Generated by Django 3.1 on 2020-08-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
