# Generated by Django 3.1 on 2020-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='New Title', max_length=200),
        ),
    ]
